### ISSUE TITLE
Techrate Shake hands with scammers 

### ISSUE THREAD

**Issue by dieptang** [TechRate/Smart-Contract-Audits#10]
I know many fug project/scammers are valid audit by the company call "Techrate", they offers to the scammers the pdf file with valid audit information without checking anything, they just got paid and give the scammers the valid audit. 

Today, we lose +500 BNB on the valid audited project call "PiggyApp Finance". Here is information:
≠===================
Hey there dear community members! PiggyAppFinance project is audited and listed, check the report by link below and stay safe 😎

Audit report ✅: https://github.com/TechRate/Smart-Contract-Audits/blob/main/PiggyAppFinance.pdf 

Projects website 🌐:  https://piggyapp.finance/  

Projects telegram chat 📬:   https://t.me/piggyapp_finance 

Projects twitter 📱:  https://twitter.com/PiggyappFinance  

Techrate's GitHub 🎗: https://github.com/TechRate/Smart-Contract-Audits

=======================≠

DONT TRUST TECHRATE ANYMORE!!!

**Comment by ESalyakhov** [comment]
Hey there dear community members! 

We get the request why PiggyFinance project end up scam and how did we miss it. 

Please take into consideration that we audit ONLY the contracts provided in the report. 
PiggyFinance requested the audit of their SALE contract only. 

It's a simple 300 line code saying that if you transfer the funds you will get the tokens. Only this logic is realzied in this contract and it was checked by us. So all who actually sent the funds to this contract received the tokens of this project that they wanted to buy the tokens from. 

We don't know any other PiggyFinance contracts and this Sale contract's logic is realized exactly as expected, send funds - get tokens instead. 

What were the expectations of the community from this project and how Piggy promised to operate with the funds we absolutely don't know since we are the Auditing firm and check the code of the contract only, not the advisory or investment platform. 

So please don't just invest in the project if it says that it's audited. Open the report, check issues in the report, check contract that is audited, check the contract that you're investing in and stay safe.

**Comment by ru17crypto** [comment]
Hi @dieptang, thank you for the information. Do you think Lavacake is a similar scam? https://github.com/TechRate/Smart-Contract-Audits/blob/main/LavaCake.pdf
